# Generated by Django 6.0.6 on 2026-06-28 01:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("empleos", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="candidatoprofile",
            name="nombre_completo",
        ),
    ]
