# Generated by Django 6.0.6 on 2026-06-28 02:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("empleos", "0002_remove_candidatoprofile_nombre_completo"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="candidatoprofile",
            name="codigo_validacion",
        ),
        migrations.AddField(
            model_name="candidatoprofile",
            name="codigo_ong",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="empleos.codigoacceso",
            ),
        ),
        migrations.AddField(
            model_name="candidatoprofile",
            name="documento_identidad",
            field=models.CharField(default="123", max_length=30, unique=True),
            preserve_default=False,
        ),
    ]
