# Generated by Django 6.0.6 on 2026-06-29 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("empleos", "0003_remove_candidatoprofile_codigo_validacion_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="ofertaempleo",
            name="requisitos",
            field=models.TextField(
                default="", help_text="Separados por comas o líneas"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="ofertaempleo",
            name="salario",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
