# Generated by Django 6.0.6 on 2026-07-01 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("empleos", "0004_ofertaempleo_requisitos_ofertaempleo_salario"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="ofertaempleo",
            name="ubicacion",
        ),
        migrations.AddField(
            model_name="ofertaempleo",
            name="estado",
            field=models.CharField(
                blank=True,
                help_text="Estado de Venezuela donde se ubica el empleo",
                max_length=100,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="ofertaempleo",
            name="municipio",
            field=models.CharField(
                blank=True,
                help_text="Municipio donde se ubica el empleo",
                max_length=100,
                null=True,
            ),
        ),
    ]
